FROM node:18

# התקנת LibreOffice (נחוץ להמרת Word ל־PDF)
RUN apt-get update && apt-get install -y libreoffice

# תקיית עבודה
WORKDIR /app

# העתקת הקוד
COPY . .

# התקנת תלויות בשרת
WORKDIR /app/server
RUN npm install

# התקנת תלויות ו-build ל-React (לקוח)
WORKDIR /app/client
RUN npm install && npm run build

# העברת ה-build של React ל-public של Node
WORKDIR /app/server
RUN mkdir -p public && cp -r ../client/build/* public/

# פתיחת פורט של השרת
EXPOSE 3001

# הפעלת השרת
CMD ["node", "express.js"]
